// Generated by Wrangler on Thu Jul 25 2024 10:55:44 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH0_CLIENT_ID: string;
	AUTH0_CLIENT_SECRET: string;
	AUTH0_ISSUER: string;
	NEXTAUTH_SECRET: string;
	DATABASE: D1Database;
	AI: Ai;
}
